name: key_value_store_web
description: A multiplatform key-value store implementation for web.
version: 1.0.0-nullsafety
homepage: https://github.com/roughike/multiplatform_key_value_store
author: Iiro Krankka <iiro.krankka@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  key_value_store:
    git:
      url: git://github.com/ibedek/multiplatform_key_value_store.git
      path: key_value_store

dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  build_web_compilers: ^2.16.4
  test: ^1.16.5
  mockito: ^5.0.0
